// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OgrenciBilgiSistemi.Data;

#nullable disable

namespace OgrenciBilgiSistemi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.Bolum", b =>
                {
                    b.Property<int>("bolumID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bolumID"));

                    b.Property<string>("bolumAd")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("fakulteID")
                        .HasColumnType("int");

                    b.HasKey("bolumID");

                    b.HasIndex("fakulteID");

                    b.ToTable("tBolum");

                    b.HasData(
                        new
                        {
                            bolumID = 1,
                            bolumAd = "Bilgisayar Mühendisliği",
                            fakulteID = 1
                        },
                        new
                        {
                            bolumID = 2,
                            bolumAd = "Elektrik-Elektronik Mühendisliği",
                            fakulteID = 1
                        },
                        new
                        {
                            bolumID = 3,
                            bolumAd = "Matematik",
                            fakulteID = 2
                        });
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.Ders", b =>
                {
                    b.Property<int>("dersID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("dersID"));

                    b.Property<string>("dersAd")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("dersKodu")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("kredi")
                        .HasColumnType("int");

                    b.HasKey("dersID");

                    b.ToTable("tDers");

                    b.HasData(
                        new
                        {
                            dersID = 1,
                            dersAd = "Programlama Temelleri",
                            dersKodu = "BIL101",
                            kredi = 5
                        },
                        new
                        {
                            dersID = 2,
                            dersAd = "Veri Tabanı Yönetimi",
                            dersKodu = "BIL102",
                            kredi = 4
                        },
                        new
                        {
                            dersID = 3,
                            dersAd = "Matematik I",
                            dersKodu = "MAT101",
                            kredi = 6
                        });
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.Fakulte", b =>
                {
                    b.Property<int>("fakulteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("fakulteID"));

                    b.Property<string>("fakulteAd")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("fakulteID");

                    b.ToTable("tFakulte");

                    b.HasData(
                        new
                        {
                            fakulteID = 1,
                            fakulteAd = "Mühendislik Fakültesi"
                        },
                        new
                        {
                            fakulteID = 2,
                            fakulteAd = "Fen Edebiyat Fakültesi"
                        });
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.Ogrenci", b =>
                {
                    b.Property<int>("ogrenciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ogrenciID"));

                    b.Property<string>("ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("bolumID")
                        .HasColumnType("int");

                    b.Property<string>("soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ogrenciID");

                    b.HasIndex("bolumID");

                    b.ToTable("tOgrenci");
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.OgrenciDers", b =>
                {
                    b.Property<int>("ogrenciID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("dersID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int?>("final")
                        .HasColumnType("int");

                    b.Property<int?>("vize")
                        .HasColumnType("int");

                    b.Property<string>("yariyil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("yil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ogrenciID", "dersID");

                    b.HasIndex("dersID");

                    b.ToTable("tOgrenciDers");
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.Bolum", b =>
                {
                    b.HasOne("OgrenciBilgiSistemi.Models.Fakulte", "Fakulte")
                        .WithMany("Bolumler")
                        .HasForeignKey("fakulteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fakulte");
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.Ogrenci", b =>
                {
                    b.HasOne("OgrenciBilgiSistemi.Models.Bolum", "Bolum")
                        .WithMany("Ogrenciler")
                        .HasForeignKey("bolumID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bolum");
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.OgrenciDers", b =>
                {
                    b.HasOne("OgrenciBilgiSistemi.Models.Ders", "Ders")
                        .WithMany("OgrenciDersler")
                        .HasForeignKey("dersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OgrenciBilgiSistemi.Models.Ogrenci", "Ogrenci")
                        .WithMany("OgrenciDersler")
                        .HasForeignKey("ogrenciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ders");

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.Bolum", b =>
                {
                    b.Navigation("Ogrenciler");
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.Ders", b =>
                {
                    b.Navigation("OgrenciDersler");
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.Fakulte", b =>
                {
                    b.Navigation("Bolumler");
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.Ogrenci", b =>
                {
                    b.Navigation("OgrenciDersler");
                });
#pragma warning restore 612, 618
        }
    }
}
